# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-13 16:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_sets'),
    ]

    operations = [
        migrations.AddField(
            model_name='sets',
            name='text',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sets',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
