# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-13 17:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20171213_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='sets',
            name='pic',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='pic_folder/'),
            preserve_default=False,
        ),
    ]
