# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-17 12:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0010_auto_20171217_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sets',
            name='name',
        ),
        migrations.AddField(
            model_name='sets',
            name='author',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
