# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-17 15:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_sets_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photos', verbose_name='Photo')),
            ],
        ),
        migrations.RemoveField(
            model_name='sets',
            name='pic',
        ),
        migrations.AddField(
            model_name='photo',
            name='sets',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Sets'),
        ),
    ]
