# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-17 16:19
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20171217_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(default='popss'),
            preserve_default=False,
        ),
    ]
