# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-17 16:41
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='sets',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
