# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-21 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_auto_20171221_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='sets',
            name='age',
            field=models.CharField(default='123', max_length=8),
            preserve_default=False,
        ),
    ]
