# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-21 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_sets_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='sets',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
