# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-21 13:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_remove_activities_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='sets',
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
