# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-21 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_auto_20171221_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activities',
            name='author',
        ),
        migrations.AddField(
            model_name='sets',
            name='brief',
            field=models.CharField(default='sdf', max_length=3),
            preserve_default=False,
        ),
    ]
