# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-21 14:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_auto_20171221_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='sets',
            field=models.ForeignKey(default='sdf', on_delete=django.db.models.deletion.CASCADE, to='blog.Sets', to_field='brief'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sets',
            name='brief',
            field=models.CharField(default='sdf', max_length=3, unique=True),
        ),
    ]
