# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-21 14:30
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_auto_20171221_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
