# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-21 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_auto_20171221_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='sets',
            name='main_image',
            field=models.ImageField(default='photos/1.jpeg', upload_to=''),
        ),
    ]
